language: node_js
node_js:
  - 13

services:
  - docker

# Scripts to be run such as test
before_script:
  - echo "Travis Run Project 3"
  - echo "Test Travis"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend hang050697/udagram-frontend:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed hang050697/udagram-api-feed:v3
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user hang050697/udagram-api-user:v1git 
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy hang050697/reverseproxy:v3

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hang050697/udagram-api-feed:v3
  - docker push hang050697/udagram-api-user:v1
  - docker push hang050697/udagram-frontend:v1
  - docker push hang050697/reverseproxy:v3